name: TheDrinkist
favicon: null
layout_spectrum: 0.3063646941445768
typography_spectrum: 0.5860466912854463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.46321419323794544
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.8079811190254986
purpose: []
